version: '3'

services:
  app:
    env_file: .env
    image: 'acherrydev/codexrepo:latest'
    environment:
      spring.datasource.url: "jdbc:postgresql://wonder-bittern-8245.8nj.cockroachlabs.cloud:26257/matrix1?sslmode=require"
      spring.datasource.username: "${POSTGRES_USER1}"
      spring.datasource.password: "${POSTGRES_PASSWORD1}"
    ports:
      - "8080:8080"
